#!/usr/bin/env bash

# A script to create the gold files needed for SMRF
# Run this script in the main smrf directory, the config
# file will put the outputs in the correct place
#
# Run as:
#     $ ./tests/Lakes/gold/make_gold_lakes

read -r -p "Recreating Lakes gold standard, are you sure? [y/N] " response
if [[ "$response" = "yes" || "$response" = "y" ]]
then
    echo "Updating Lakes gold files"
    echo "Removing old gold files"
    rm tests/Lakes/gold/topo.nc

    echo "Running generate_topo"
    generate_topo tests/Lakes/gold/gold_config.ini

    if [ $? == 0 ]; then
        echo "Cleaning up"
        rm -rf tests/Lakes/gold/tmp
    fi
else
    echo "Lakes gold files not updated"
fi