# Config file for automatic testing at travis-ci.org

sudo: required

language: python

services:
  - docker

before_install:
  - docker build  -t usdaarsnwrc/basin_setup .

script:
  docker run -it --rm --entrypoint make --workdir /code/basin_setup usdaarsnwrc/basin_setup test

